### ISSUE TITLE
Bug: Error After Connecting with Chameleon Ultra

### ISSUE THREAD

**Issue by Mikegim** [taichunmin/chameleon-ultra.js#115]
**Everything was working correctly until about two days ago.** 

![image](https://github.com/taichunmin/chameleon-ultra.js/assets/25134471/ef9fa6e0-3bea-4303-a5da-bf74692c0c20)

**Now, when I try to pair the Chameleon Ultra, I get an error message.**

![image](https://github.com/taichunmin/chameleon-ultra.js/assets/25134471/171faa2f-bb40-4490-83bc-e6aafeccd34d)

**Comment by taichunmin** [comment]
Can you open the devtools (F12) > console page, reproduce the error, and capture the error logged in the devtools' console page?

**Comment by Mikegim** [comment]
Thank you, this morning I retook the test and the page works perfectly.
Thank you for the quick solution.


Il giorno ven 7 giu 2024 alle ore 05:23 戴均民 ***@***.***> ha
scritto:
